project:
  type: book
  output-dir: _book
  
book:
  title: "Nedbyggingsregnskap for friluftslivsområder i Norge "
  author: "NINA"
  description: | 
    Nedbyggingsregnskap tabeller som kartlegger det årlige og kumulative arealforbruket i perioden 2018–2024 innenfor: (i) kommuner og fylker; og (ii) friluftsområder som er merket som «viktige» og «svært viktige». Vi presenterer også arealet av «spesielt viktig natur» som er gått tapt til arealforbruk innenfor (i) og (ii).
  repo-url: https://github.com/NINAnor/recereation_encroachment_accounts
  repo-branch: main
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - innledning.qmd
    - src/code/accounting-tables_display.qmd
    
format:
  html: 
    theme: 
    - cosmo
    - NINAstyle.scss
    
    code-link: true

bibliography: references.bib
csl: NINArefStyle.csl
